In [1]:
from calibratedRecs.calibration import Calibration

In [2]:
from dynamicTasteDistortion.dataset_loader import get_ml_df

data_type = "ml"
size = "s"

raw_df = get_ml_df(size)

Skipping: 'dynamicTasteDistortion/data/movielens/raw/ml_s/' already exists and contains files.
Joining movies data with ratings data...
Preprocessing dataset...

## building TWB weigthing


Methodology: The weight of a rating done at timestamp i, where, for this user, the most recent timestamp is given by a and the oldest by z

$$
    w_{twb} = \frac{i-a}{z-a}
$$

In [19]:
raw_df

,item,genres,user,rating,timestamp,binarized_rating,max_timestamp,min_timestamp,twb
0,1,"[animation, children's, comedy]",1,5,978824268,1,978824351,978300019,0.999842
1,1,"[animation, children's, comedy]",6,4,978237008,1,978239019,978236075,0.316916
2,1,"[animation, children's, comedy]",8,4,978233496,1,978247143,978228789,0.256456
3,1,"[animation, children's, comedy]",9,5,978225952,1,978226678,978224859,0.600880
4,1,"[animation, children's, comedy]",10,5,978226474,1,980638688,978224375,0.000869
...,...,...,...,...,...,...,...,...,...
1000204,3952,"[drama, thriller]",5812,4,992072099,1,1042306493,957937089,0.404590
1000205,3952,"[drama, thriller]",5831,3,986223125,0,1033774570,957887135,0.373395
1000206,3952,"[drama, thriller]",5837,4,1011902656,1,1011902688,957841680,0.999999
1000207,3952,"[drama, thriller]",5927,1,979852537,0,979852584,957272034,0.999998
1000208,3952,"[drama, thriller]",5998,4,1001781044,1,1001832291,956847815,0.998861

In [ ]:
raw_df.groupby("user").agg({"timestamp": ["max", "min"]})

      user  timestamp
                  max        min
0        1  978824351  978300019
1        2  978300174  978298124
2        3  978298504  978297018
3        5  978246585  978241072
4        6  978239019  978236075
...    ...        ...        ...
5284  6035  956713640  956710846
5285  6036  956755196  956709349
5286  6037  956801840  956708997
5287  6039  956758029  956705158
5288  6040  998315055  956703932

[5289 rows x 3 columns]